skit_pipelines/components/fetch_calls.py
skit_pipelines/components/tag_calls.py
skit_pipelines/pipelines/fetch_n_tag_calls_pipeline.py
skit_pipelines/pipelines/tag_calls_pipeline.py

- recurring parameter for fetch_n_tag calls pipeline for repeating task
- upload to multiple tog jobs (job_ids is now a comma separated list of job id)

Automated fetch-n-tag recurring pipeline + multiple job uploads

---

poetry.lock
pyproject.toml
skit_pipelines/components/__init__.py
skit_pipelines/components/gen_confusion_matrix.py
skit_pipelines/pipelines/eval_voicebot_xlmr_pipeline.py

create a component `gen_confusion_matrix` and add it to the `eval_voicebot_xlmr_pipeline` pipeline to generate the confusion matrix for intent performance.

add: generate confusion matrix in eval_voicebot_xlmr_pipeline

---

skit_pipelines/components/fetch_tagged_dataset.py
skit_pipelines/pipelines/irr_from_tog/__init__.py

and have used in irr_from_tog.
lmk if this is alright, will test it out.

offset for pulling last n days in fetch_tagged_dataset op

---

skit_pipelines/components/eevee_irr_with_yamls.py
skit_pipelines/pipelines/irr_from_tog/__init__.py

using the offset, tested to make sure the pipeline works with `start_date_offset` etc.

fixes to make the pipeline working recurrently from slack.

---

skit_pipelines/components/tag_calls/__init__.py
skit_pipelines/pipelines/fetch_n_tag_calls/__init__.py
skit_pipelines/pipelines/tag_calls/__init__.py

This branch will add some temporary logic to push data to labelstudio.

update: force route tagging requests to labelstudio.

---

skit_pipelines/components/gen_eer_metrics.py
skit_pipelines/components/modify_entities/modify_predictions.py
skit_pipelines/components/modify_tog_entities.py

just a fix, pipeline was breaking when:
* we faced nan instead of json in entity predictions
* we face interval types inappropriate format for eevee.

fixes involving nan + adjusting for interval types

---

CONTRIBUTING.md
Makefile
docker_build_dev_image.dvc
pipeline_secrets.dvc
poetry.lock
pyproject.toml
run_pipeline.py
skit_pipelines/api/models/__init__.py
skit_pipelines/components/__init__.py
skit_pipelines/components/download_from_s3.py
skit_pipelines/components/tag_calls/labelstudio.py
skit_pipelines/pipelines/eval_asr_pipeline/__init__.py
skit_pipelines/pipelines/eval_voicebot_xlmr_pipeline/__init__.py
skit_pipelines/pipelines/train_voicebot_intent_model_xlmr/__init__.py

breaking download_from_s3 to downstream components for downloading csv, directory and file
bonus: download_csv_from_s3 - this component also supports comma-separated list of CSV URIs as input.

breaking download_from_s3 into downstream components

---

skit_pipelines/components/eevee_irr_with_yamls.py
skit_pipelines/components/extract_info_from_dataset.py
skit_pipelines/components/push_irr_to_postgres.py
skit_pipelines/pipelines/irr_from_tog/__init__.py

changes to existing components to support labelstudio tagged datasets for intents.
cc: @Sonal-Kiran @lohith-anandan

irr fixes for labelstudio datasets

---

skit_pipelines/components/__init__.py
skit_pipelines/components/preprocess/extract_true_transcript_labels_to_txt/__init__.py
skit_pipelines/components/preprocess/extract_true_transcript_labels_to_txt/utils.py
skit_pipelines/pipelines/asr_tune/__init__.py

add support for tog_job_id inputs for corpus and validation corpus

Asr tune pipeline enhancements

---

poetry.lock
pyproject.toml

fixes [this](https://vernacular-ai.atlassian.net/browse/PL-749) issue.

downgrade google-auth-oauthlib to 0.4.6

---

pipeline_secrets.dvc
poetry.lock
pyproject.toml
skit_pipelines/components/fetch_tagged_data_label_store/__init__.py
skit_pipelines/components/tag_calls/__init__.py
skit_pipelines/components/tag_calls/labelstudio.py
skit_pipelines/components/tag_calls/tog.py
skit_pipelines/pipelines/fetch_calls_n_upload_tog_and_sheet/__init__.py
skit_pipelines/pipelines/fetch_n_tag_calls/__init__.py
skit_pipelines/pipelines/fetch_n_tag_turns_and_calls/__init__.py
skit_pipelines/pipelines/fetch_tagged_data_from_labelstore/__init__.py
skit_pipelines/pipelines/tag_calls/__init__.py

- modify pipelines involving tag_calls component to accept a mandatory data_label component
- add ability to filter tagged data on multiple data_labels
- change labelstore output column names in accordance to existing format

data_label addition

---

Dockerfile

Reverts skit-ai/skit-pipelines#90

Revert "cache the poetry install step for faster docker builds and dev experience"

---

skit_pipelines/components/upload_for_call_and_slot_tagging/__init__.py
skit_pipelines/constants.py

making console url, region specific for call & slot tagging jobs.

---

skit_pipelines/components/modify_entities/duckling_inference.py
skit_pipelines/components/modify_entities/modify_predictions.py
skit_pipelines/components/modify_tagged_entities.py

fixing upstream column names for entity tagged dataset

---

skit_pipelines/components/retrain_slu_from_repo.py
skit_pipelines/pipelines/retrain_slu/__init__.py

Reverts skit-ai/skit-pipelines#100

Revert "Customization repo integration for retraining pipeline"

---

skit_pipelines/components/fetch_gpt_intent_prediction/__init__.py
skit_pipelines/components/fetch_gpt_intent_prediction/constants.py
skit_pipelines/constants.py
skit_pipelines/pipelines/fetch_n_tag_calls/__init__.py

TODO: Extracting necessary prompt variables as Growthbook FF will be handled as part of a follow-up PR

Extend GPT support for fetch_n_tag_calls and update prompts

---

skit_pipelines/components/upload_for_call_and_slot_tagging/__init__.py
skit_pipelines/constants.py

have locally tested it out with IN (to preserve console call report for now, with emeritus) & US with studio calls (for template_id = 100). both are working fine from call_link generation pov.
please help me with getting this PR reviewed and merged.

adding support for Studio Calls for US call & slot eval tagging.

---

skit_pipelines/components/__init__.py
skit_pipelines/components/download_repo.py
skit_pipelines/components/retrain_slu_from_repo.py
skit_pipelines/components/retrain_slu_from_repo_old.py
skit_pipelines/constants.py
skit_pipelines/pipelines/__init__.py
skit_pipelines/pipelines/retrain_slu/__init__.py
skit_pipelines/pipelines/retrain_slu_old/__init__.py

Changes:
- Creates a new pipelines `retrain_slu_old` which should operate exactly how `retrain_slu` does right now on `master`.
- `retrain_slu` is refactored according to changes expected in `core-slu-service` for train and test workflows.
Verification runs:
- [Test run](https://kubeflow.skit.ai/_/pipeline/?ns=skit#/runs/details/c69032ea-e41e-4e82-a941-38ad47cf82fe) on small data
- [Run](https://kubeflow.skit.ai/_/pipeline/?ns=skit#/runs/details/c69032ea-e41e-4e82-a941-38ad47cf82fe) on complete data of 1 project
- [Run](https://kubeflow.skit.ai/_/pipeline/?ns=skit#/runs/details/51b747e6-4076-4c57-b66e-28f284f7b201) for old pipeline on same complete data for 1 project

Refactor retraining pipelines for new SLU architecture

---

skit_pipelines/components/retrain_slu_from_repo.py

Streaming logs wasn't working. Adopts the suggestion from here - https://github.com/conda/conda/issues/9412#issuecomment-719759077

Fix logs streaming during train and test

---

CHANGELOG.md
Dockerfile
pyproject.toml

pin down chrome broweser and driver version

---

skit_pipelines/api/slack_bot.py
skit_pipelines/api/validate_input.py

**Why**
Start process of validating inputs before scheduling pipelines
**What**
Skeleton of how validation should happen and some basic use-cases. List would keep getting updated as and when more cases are identified
**Links**
[Ticket](https://vernacular-ai.atlassian.net/browse/PL-1426?atlOrigin=eyJpIjoiMmQzOWEwMmU1OWExNDdjNjk1ZGQzYjM4MzYwNjI4Y2YiLCJwIjoiaiJ9)

Add skeleton and basic validations for input parameters

---

skit_pipelines/components/create_mr.py
skit_pipelines/components/retrain_slu_from_repo/__init__.py
skit_pipelines/components/retrain_slu_from_repo/comparision_report_generator.py
skit_pipelines/components/retrain_slu_from_repo/utils.py
skit_pipelines/pipelines/retrain_slu/__init__.py

- Add confusion matrix comparison
- Refactor code
- Remove extra files from output

Add comparision confusion matrix between trained model and production

---

skit_pipelines/components/retrain_slu_from_repo/__init__.py

**Why**
Post this [PR](https://github.com/skit-ai/skit-pipelines/pull/120), data.dvc file is not getting added to the PR post SLU retraining
**Links**
[Jira](https://vernacular-ai.atlassian.net/jira/software/projects/PLR/boards/198?assignee=620e14ae682913007086681e&selectedIssue=PLR-79)

Delete lock file

---

CHANGELOG.md
pyproject.toml
skit_pipelines/components/retrain_slu_from_repo/comparision_report_generator.py

minor fix in comparison report generator.
Problem - The intent list is not coming in comparison report
Example of Error File
precision,recall,f1-score,support
"(0.0, 0.0)","(0.0, 0.0)","(0.0, 0.0)","(21.0, 21.0)"
"(0.0, 0.0)","(0.0, 0.0)","(0.0, 0.0)","(2.0, 2.0)"
"(0.9565637065637066, 0.9629268292682926)","(0.8777679362267493, 0.8742249778565102)","(0.915473441108545, 0.916434540389972)","(1129.0, 1129.0)"
"(0.8557046979865772, 0.8711864406779661)","(0.913978494623656, 0.921146953405018)","(0.8838821490467937, 0.8954703832752613)","(279.0, 279.0)"
"(0.0, 0.0)","(0.0, 0.0)","(0.0, 0.0)","(0.0, 0.0)"
"(0.1707317073170731, 0.1395348837209302)","(0.875, 0.75)","(0.2857142857142857, 0.2352941176470588)","(8.0, 8.0)"
"(0.0, 0.0)","(0.0, 0.0)","(0.0, 0.0)","(24.0, 24.0)"
"(0.0, 0.0)","(0.0, …

minor fix in comparision_report_generator.

---

skit_pipelines/components/sample_conversations_generator/__init__.py
skit_pipelines/pipelines/generate_sample_conversations/__init__.py

This reverts commit 4d9507f5646ba84fa2c9af487566f1752f9afbec.

Revert "Support for new format of scenarios (#134)"

---

CHANGELOG.md
pyproject.toml
skit_pipelines/components/zip_files_and_notify.py
skit_pipelines/pipelines/generate_sample_conversations/__init__.py

Add support to display a random conversation from the generated conversations on the slack

Add support to display conversation

---

CHANGELOG.md
pyproject.toml

Reverts skit-ai/skit-pipelines#138

Revert "Update the skit-calls version"

---

CHANGELOG.md
poetry.lock
pyproject.toml
skit_pipelines/components/download_repo.py

- Fix issue with retrain_slu_old pipeline due to missing import
- Fix the dependency issue with bcrypt and passlib

Fix issue with retrain_slu_old pipeline

---

CHANGELOG.md
poetry.lock
pyproject.toml
skit_pipelines/components/fetch_calls.py

- Update skit-calls version
- Fix issue with file name 
- Fix client_id data type handling

Fix fetch pipelines

---

CHANGELOG.md
pyproject.toml
skit_pipelines/components/zip_files_and_notify.py

Update the file name to be skipped in the sample conversation to be displayed in slack

Fix issue sample conv display

---

CHANGELOG.md
poetry.lock
pyproject.toml
skit_pipelines/components/upload_for_call_and_slot_tagging/__init__.py

adding changes based on: https://github.com/skit-ai/skit-calls/pull/32

[QT-131] call_tagging: adding blocking_disposition

---

CHANGELOG.md
pipeline_secrets.dvc
pyproject.toml
skit_pipelines/pipelines/evaluate_slu/__init__.py

- Remove GPU node selector for evaluation pipelines
- Update the Gitlab token in the .env files

Fix node selector and Gitlab token issue

---

CHANGELOG.md
Dockerfile
pyproject.toml

Fix the chrome and chrome driver installation failure during image build due to the change in the respective downloading url changes

Update the chrome version

---

CHANGELOG.md
pyproject.toml

Update the changelog and pyproject.toml

Update the changelog

---

CHANGELOG.md
Dockerfile
pyproject.toml
skit_pipelines/utils/cookies.py

- Add missing dependency
- Remove chrome installation in code and point to an executable

Fix dependency and chrome installer code

---

CHANGELOG.md
pyproject.toml
skit_pipelines/components/upload_for_call_and_slot_tagging/__init__.py

Replace console links with Studio links in the pipelines

Replace console links with studio links

---

CHANGELOG.md
pipeline_secrets.dvc
pyproject.toml

- Update AWS credentials
- Update Github personal access token

Update aws and github creds

---

CHANGELOG.md
Dockerfile
poetry.lock
pyproject.toml

Fix issue due python version mismatch in corresponding slu repos such as core-slu and customization repos

fix: issue due python version mismatch in repos
